apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  strategy: {}
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        command:
          - sleep
          - "3600"    
        name: busybox
        imagePullPolicy: IfNotPresent
        resources:
          limits: 
            memory: 1024Mi
            cpu: 1
          requests: 
            memory: 500Mi
            cpu: 500m




