apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-deployment
spec:
  replicas: 3  # numero de replicas que você quiser
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario-container
        image: onlinepublic/supermario
        ports:
        - containerPort: 80
        resources:
          limits: 
            memory: 1024Mi
            cpu: 1
          requests: 
              memory: 512Mi
              cpu: 0.5
  